# ---------------- Special Tokens ----------------
special_tokens_mapping_to_desc = {
    "AGE_15_20_years": "Here's the patient who is between 15-20 years old",
    "AGE_20_25_years": "Here's the patient who is between 20-25 years old",
    "AGE_25_30_years": "Here's the patient who is between 25-30 years old",
    "AGE_30_35_years": "Here's the patient who is between 30-35 years old",
    "AGE_35_40_years": "Here's the patient who is between 35-40 years old",
    "AGE_40_45_years": "Here's the patient who is between 40-45 years old",
    "AGE_45_50_years": "Here's the patient who is between 45-50 years old",
    "AGE_50_55_years": "Here's the patient who is between 50-55 years old",
    "AGE_55_60_years": "Here's the patient who is between 55-60 years old",
    "AGE_60_65_years": "Here's the patient who is between 60-65 years old",
    "AGE_65_70_years": "Here's the patient who is between 65-70 years old",
    "AGE_70_75_years": "Here's the patient who is between 70-75 years old",
    "AGE_75_80_years": "Here's the patient who is between 75-80 years old",
    "AGE_80_85_years": "Here's the patient who is between 80-85 years old",
    "AGE_85_90_years": "Here's the patient who is between 85-90 years old",
    "AGE_90_95_years": "Here's the patient who is between 90-95 years old",
    "AGE_95_100_years": "Here's the patient who is between 95-100 years old",
    "DEATH": "This token represents the death of the patient",
    "END_RECORD": "This token represents the end of the record",
    "END_VISIT": "This token represents the end of the visit",
    "MARITAL_STATUS_DIVORCED": "This token represents that the marital status of the patient is divorced",
    "MARITAL_STATUS_MARRIED": "This token represents that the marital status of the patient is married",
    "MARITAL_STATUS_SINGLE": "This token represents that the marital status of the patient is single",
    "MARITAL_STATUS_UNKNOWN": "This token represents that the marital status of the patient is unknown",
    "MARITAL_STATUS_WIDOWED": "This token represents that the marital status of the patient is widowed",
    "PADDING": "This token does not have any meaning, just used for padding",
    "RACE_ASIAN": "This token represents that the race of the patient is asian",
    "RACE_BLACK": "This token represents that the race of the patient is black",
    "RACE_HISPANIC": "This token represents that the race of the patient is hispanic",
    "RACE_OTHER": "This token represents that the race of the patient is other",
    "RACE_UNKNOWN": "This token represents that the race of the patient is unknown",
    "RACE_WHITE": "This token represents that the race of the patient is white",
    "SEX_F": "This token represents that the sex of the patient is female",
    "SEX_M": "This token represents that the sex of the patient is male",
    "START_RECORD": "This token represents the start of the record",
    "START_VISIT": "This token represents the start of the visit",
    "YEAR_2005": "This token represents that the year of the patient record is 2005",   
    "YEAR_2006": "This token represents that the year of the patient record is 2006",
    "YEAR_2007": "This token represents that the year of the patient record is 2007",
    "YEAR_2008": "This token represents that the year of the patient record is 2008",
    "YEAR_2009": "This token represents that the year of the patient record is 2009",
    "YEAR_2010": "This token represents that the year of the patient record is 2010",
    "YEAR_2011": "This token represents that the year of the patient record is 2011",
    "YEAR_2012": "This token represents that the year of the patient record is 2012",
    "YEAR_2013": "This token represents that the year of the patient record is 2013",
    "YEAR_2014": "This token represents that the year of the patient record is 2014",
    "YEAR_2015": "This token represents that the year of the patient record is 2015",
    "YEAR_2016": "This token represents that the year of the patient record is 2016",
    "YEAR_2017": "This token represents that the year of the patient record is 2017",
    "YEAR_2018": "This token represents that the year of the patient record is 2018",
    "YEAR_2019": "This token represents that the year of the patient record is 2019",
    "YEAR_2020": "This token represents that the year of the patient record is 2020",
    "_Q1": "This token represents that the lab test result is the first quarter of its range",
    "_Q10": "This token represents that the lab test result is the tenth quarter of its range",
    "_Q2": "This token represents that the lab test result is the second quarter of its range",
    "_Q3": "This token represents that the lab test result is the third quarter of its range",
    "_Q4": "This token represents that the lab test result is the fourth quarter of its range",
    "_Q5": "This token represents that the lab test result is the fifth quarter of its range",
    "_Q6": "This token represents that the lab test result is the sixth quarter of its range",
    "_Q7": "This token represents that the lab test result is the seventh quarter of its range",
    "_Q8": "This token represents that the lab test result is the eighth quarter of its range",
    "_Q9": "This token represents that the lab test result is the ninth quarter of its range",
}

# ---------------- Time Gap Tokens ----------------
timegap_token_mapping_to_desc = {
    "_12h-1d": "This token represents that the time of the event is between 12 hours and 1 day",
    "_15m-1h": "This token represents that the time of the event is between 15 minutes and 1 hour",
    "_1d-3d": "This token represents that the time of the event is between 1 day and 3 days",
    "_1h-2h": "This token represents that the time of the event is between 1 hour and 2 hours",
    "_1mt-3mt": "This token represents that the time of the event is between 1 month and 3 months",
    "_1w-2w": "This token represents that the time of the event is between 1 week and 2 weeks",
    "_2h-6h": "This token represents that the time of the event is between 2 hours and 6 hours",
    "_2w-1mt": "This token represents that the time of the event is between 2 weeks and 1 month",
    "_3d-1w": "This token represents that the time of the event is between 3 days and 1 week",
    "_3mt-6mt": "This token represents that the time of the event is between 3 months and 6 months",
    "_5m-15m": "This token represents that the time of the event is between 5 minutes and 15 minutes",
    "_6h-12h": "This token represents that the time of the event is between 6 hours and 12 hours",
    "_<=5m": "This token represents that the time of the event is less than 5 minutes",
    "_>6mt": "This token represents that the time of the event is greater than 6 months"
}